### ISSUE TITLE
[1.10.2 - 1.0.0] Pipe render screws up?

### ISSUE THREAD

**Issue by VallenFrostweaver** [Flaxbeard/ImmersivePetroleum#7] opened 2017-05-24 16:32 UTC
I don't experience this in IE alone but adding in this expansion I get a strange pipe render when making pipe longer than a few pieces in a line (no branch offs).  Existing pipe doesn't experience this. This is also seen in the manual when I spin the image. See below.
![24-05-17 5-04-06 pm](https://cloud.githubusercontent.com/assets/13642054/26414346/d15349bc-40a6-11e7-8559-f314b9152c06.png)

**Comment by Flaxbeard** [comment] 2017-05-24 17:07
Hmm - can you give steps to reproduce this bug? The manual seems to render fine for me.

**Comment by Flaxbeard** [comment] 2017-05-24 17:16
So I've been able to reproduce the bug outside of my dev environment but not within it - I'll see if I can figure out why.

**Comment by VallenFrostweaver** [comment] 2017-05-24 19:55
Good luck. :)

**Comment by Flaxbeard** [comment] 2017-05-25 20:25
Blu has confirmed that this seems to be an occasional issue with base Immersive Engineering in 1.10, so I'm closing it for now.

**Closed by Flaxbeard** 2017-05-25 20:25 UTC
Labels: bug, visual

**Comment by VallenFrostweaver** [comment] 2017-05-26 06:04
Ah. My bad then. Sorry about that.
