### ISSUE TITLE
[1.16.3] Crash caused by loading pumpjack in manual

### ISSUE THREAD

**Issue by ItsWiley** [Flaxbeard/ImmersivePetroleum#187] opened 2020-12-09 17:59 UTC
**IE Version:** 1.16.3-4.1.1-127
**IP Version:** 1.16.3-3.0.0
**Forge Version:** 34.1.42
**Game Version:** 1.16.3

When loading the entire pumpjack in the engineers manual by clicking the square icon on the left of your manual the game crashes . Linked below are four crash reports from two different users. The issue happens on both single player worlds and dedicated servers. Server console lists the reason for player leaving simply as "Disconnected." Reinstalling IE/IP do not solve the issue nor does reinstalling the entire modpack. Note that some mod versions are censored in the crash reports due to mcpaste falsely flagging them as IP addresses, I am willing to supply the full logs upon request.

**Crash 1:** https://mcpaste.io/a81abe49f722fcb1
**Crash 2:** https://mcpaste.io/f60fb6a8f5cb7603
**Crash 3:** https://mcpaste.io/0b16e539095a6db3
**Crash 4:** No Report

Crash 1 and 2 were performed by a user on a dedicated server. Crash 3 is from a different user on the same dedicated server. All three of these crashes displayed this error upon crashing. 
_The game crashed whilst rendering screen
Error: java.lang.IllegalStateException: Already building!
Exit Code: -1_

Crash 4 was done in single player by the same user as crash 1 and 2, this time it did not yield a crash report and displayed this error instead. 
_An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience.
Exit Code : 0_

**Comment by TwistedGate** [comment] 2020-12-11 10:20
Duplicate of #183

**Closed as completed by TwistedGate** 2020-12-11 10:20 UTC
